# Generated by Django 4.2.2 on 2023-07-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="penaltypoint",
            name="files",
            field=models.FileField(upload_to="files/feedBacks/"),
        ),
        migrations.AlterField(
            model_name="query",
            name="maximum",
            field=models.SmallIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="query",
            name="minimum",
            field=models.SmallIntegerField(default=1),
        ),
    ]
