# Generated by Django 4.2.2 on 2023-07-05 04:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api", "0002_alter_penaltypoint_files_alter_query_maximum_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="positivepoint",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_positives",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
